### PR TITLE
Switch to esmodule export

### PR DESCRIPTION
**Pull request by julianrubisch**
A couple of people (#11, #8) were reporting failure to import in an ESmodule setup, and as I bumped into this today myself... this seems to fix it ✌️

### CODE REVIEW

**Comment by mziru** [comment]
is there any update on merging this pr?
was running into the same issue, and this seems to be a fix.

**Comment by ZmagoD** [comment]
Same here I'm running in the this issue, it would be great if the PR was merged

**Comment by aamdani** [comment]
I'm also encountering this for a legacy JSP app that I've been modernizing. Any reason this has stalled out?

**Comment by aamdani** [comment]
Also, this [public fork](https://github.com/excid3/uppy-activestorage-upload/compare/master...Spydarlee:uppy-activestorage-upload:master) has some additions to consider around the headers and an upload emit/event name.

**Pull request merged**
